ALTER TABLE clients
ALTER COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE client_notes
ALTER COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY;


SELECT setval(
               pg_get_serial_sequence('clients', 'id'),
               COALESCE((SELECT MAX(id) FROM clients), 0) + 1,
               false
       );

SELECT setval(
               pg_get_serial_sequence('client_notes', 'id'),
               COALESCE((SELECT MAX(id) FROM client_notes), 0) + 1,
               false
       );